name: Release Flatpak

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  flatpak-release:
    name: "Build & Release"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: mensa-sh.flatpak
          manifest-path: digital.fischers.mensash.json
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: false

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: mensa-sh.flatpak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
